version: '3.7'

services:

  web:
    build:
      dockerfile: web.Dockerfile
      context: .
    container_name: web
    command: uwsgi uwsgi.ini
    restart: always
    volumes:
      - /home/calum/pytho/static:/root/pytho/static
    ports:
      - "10.147.20.37:8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:11
    container_name: db
    ports:
      - "10.147.20.37:5432:5432"
    env_file:
      - .env
    volumes:
      - /home/calum/db/data:/var/lib/postgresql/data
      - /home/calum/db/shared:/root/shared
