version: '3.7'

services:

  web:
    build:
      dockerfile: web.Dockerfile
      context: .
    container_name: web
    command: bash -c "source venv/bin/activate && uwsgi uwsgi.ini"
    restart: always
    volumes:
      - /home/calum/dev/pytho/static:/root/pytho/static
    ports:
      - "100.76.201.89:8000:8000"
    env_file:
      - .env
