version: '3.7'
services:

  pytho:
    build:
      dockerfile: web.Dockerfile
      context: .
    container_name: pytho
    command: bash -c "source venv/bin/activate && uwsgi uwsgi.ini"
    restart: always
    environment:
      - DJANGO_DEBUG=false
      - DJANGO_SETTINGS_MODULE=retirement.settings
      - SEC_USER_AGENT="CalumRussell:calum.mj.russell@gmail.com"
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - HERMES_APIKEY=${HERMES_APIKEY}

  nginx:
    build:
      args:
        - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      dockerfile: nginx.Dockerfile
      context: .
    container_name: nginx
    restart: always
    volumes:
      - $PWD/uwsgi_params.conf:/root/pytho/uwsgi_params
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "20000:80"
