version: '3.7'

services:

  nginx:
    build:
      dockerfile: nginx.Dockerfile
      context: .
    container_name: nginx
    restart: always
    volumes:
      -  /home/calum/dev/pytho/uwsgi_params:/root/pytho/uwsgi_params
      - ./nginx:/etc/nginx/nginx.conf
      - ./nginx:/etc/nginx/conf.d/nginx.conf
      -  /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
