# Generated by Django 4.0.4 on 2022-06-11 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_auto_20211112_2128"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="coverage",
            unique_together={("country_name", "name", "issuer")},
        ),
    ]
