# Generated by Django 4.0.4 on 2022-06-11 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_alter_coverage_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="coverage",
            unique_together={("country_name", "name", "currency", "issuer")},
        ),
    ]
