[package]
name = "rust_funcs"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_funcs"
crate-type = ["cdylib"]

[dependencies]

alator = { path = "./alator" }
pyo3 = { version= "0.14.5", features = ["extension-module"] }